### ISSUE TITLE
لینک عنوان فیلم در صفحه ست

### ISSUE THREAD

**Issue by MohamadSH** [sohrabafard/alaatv#3734]
![image](https://user-images.githubusercontent.com/15714168/74934296-2328e200-53fb-11ea-9a25-756e3b3a84a3.png)

![image](https://user-images.githubusercontent.com/15714168/74934301-2623d280-53fb-11ea-9e3c-2ce740f9c382.png)

**Comment by kerasus** [comment]
با تغییر در css حل شد
