### ISSUE TITLE
باگ های تبلیغات در گوشی

### ISSUE THREAD

**Issue by MohamadSH** [sohrabafard/alaatv#3801]
<div dir='rtl'>

کیفیت اچ دی تبلیغات اپ ال اس
دکمه رد کردن گنده روی صفحه می ماند مزاحم است
نشون نمیده چند ثانیه باقی مانده
انتخاب کیفیت هم تبلیغات هم فیلم کار نمی کنه

</div>

**Comment by kerasus** [comment]
مشکل انتخاب کیفیت در موبایل برطرف شد
نمایش تایمر باقیمانده و دکمه رد کردن بهبود یافت
